services:
  webapi:
    build:
      context: .
      dockerfile: ./WebApiRefreshTokenDemo/dockerfile
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ConnectionStrings__Default=Server=sqlserverdb,1433;Initial Catalog=;User ID=sa;Password=${DB_PASSWORD:?db password not set};TrustServerCertificate=true;
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD:?certificate password not set}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/WebApiRefreshTokenDemo.pfx
    env_file:
      - .env
    depends_on:
      sqlserverdb:
        condition: service_healthy
    volumes:
      - ${APPDATA}\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    ports:
      - 11433:1433
    environment:
      - ACCEPT_EULA=Y
      - TZ=America/Havana
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:?db password not set}
      - MSSQL_PID=Express
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD:?db password not set}", "-C", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
