services:
  webapi:
    build:
      context: .
      dockerfile: ./WebApiRefreshTokenDemo/dockerfile
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD:?certificate password not set}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/WebApiRefreshTokenDemo.pfx
    env_file:
      - .env
    volumes:
      - ${APPDATA}\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
